name: material_icons_font

description: Default icons font asset for Material widgets
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/material_icons_font
version: 0.1.1

flutter:
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/MaterialIcons-Regular.ttf